# Generated by Django 5.2.8 on 2025-11-20 14:10

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this purchase request', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Brief title describing the purchase request', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the purchase request')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', help_text='Current status of the purchase request', max_length=20)),
                ('current_approval_level', models.IntegerField(default=0, help_text='Current approval level (0=draft, 1=L1, 2=L2)')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount of the purchase request', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('proforma_file', models.FileField(blank=True, help_text='Uploaded proforma invoice/quotation file', null=True, upload_to='proforma/%Y/%m/')),
                ('purchase_order_file', models.FileField(blank=True, help_text='Generated purchase order file', null=True, upload_to='purchase_orders/%Y/%m/')),
                ('receipt_file', models.FileField(blank=True, help_text='Uploaded receipt file after purchase completion', null=True, upload_to='receipts/%Y/%m/')),
                ('proforma_extracted_data', models.JSONField(blank=True, help_text='AI-extracted data from proforma invoice', null=True)),
                ('purchase_order_data', models.JSONField(blank=True, help_text='Data used to generate the purchase order', null=True)),
                ('receipt_data', models.JSONField(blank=True, help_text='AI-extracted data from receipt', null=True)),
                ('receipt_validation', models.JSONField(blank=True, help_text='Receipt validation results comparing against PO', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when request was last updated')),
                ('created_by', models.ForeignKey(help_text='User who created this request', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Request',
                'verbose_name_plural': 'Purchase Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Name of the item being requested', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the item')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of items requested', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price (quantity * unit_price)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when item was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when item was last updated')),
                ('request', models.ForeignKey(help_text='The purchase request this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_requests.purchaserequest')),
            ],
            options={
                'verbose_name': 'Request Item',
                'verbose_name_plural': 'Request Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status', '-created_at'], name='purchase_re_status_26b08b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['created_by', 'status'], name='purchase_re_created_8b1dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status', 'current_approval_level'], name='purchase_re_status_fa4a5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0), ('total_amount__isnull', True), _connector='OR'), name='total_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.CheckConstraint(condition=models.Q(('current_approval_level__gte', 0), ('current_approval_level__lte', 2)), name='valid_approval_level'),
        ),
        migrations.AddConstraint(
            model_name='requestitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='requestitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='unit_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='requestitem',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gt', 0)), name='total_price_positive'),
        ),
    ]
