# Generated by Django 5.2.8 on 2025-11-20 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_level', models.IntegerField(help_text='Approval level at which action was taken (0=submission, 1=L1, 2=L2)')),
                ('action', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('UPDATED', 'Updated')], max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Approval/rejection reason or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='purchase_requests.purchaserequest')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['request', 'created_at'], name='approvals_a_request_fd53e4_idx'), models.Index(fields=['approver', '-created_at'], name='approvals_a_approve_5b55f5_idx'), models.Index(fields=['action', '-created_at'], name='approvals_a_action_bbd7e1_idx')],
            },
        ),
    ]
